// <auto-generated />
using System;
using Calls.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calls.Infrastructure.Migrations
{
    [DbContext(typeof(CallsDbContext))]
    [Migration("20251219190350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calls.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Calls.Domain.Rooms.Room", b =>
                {
                    b.OwnsMany("Calls.Domain.Rooms.RoomParticipant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.HasKey("RoomId", "UserId");

                            b1.ToTable("RoomParticipants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoomId");

                            b1.OwnsOne("Calls.Domain.Rooms.ParticipantSettings", "Settings", b2 =>
                                {
                                    b2.Property<Guid>("RoomParticipantRoomId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RoomParticipantUserId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RoomParticipantRoomId", "RoomParticipantUserId");

                                    b2.ToTable("RoomParticipants");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomParticipantRoomId", "RoomParticipantUserId");
                                });

                            b1.OwnsOne("Calls.Domain.Rooms.SmallUserInfo", "SmallUserInfo", b2 =>
                                {
                                    b2.Property<Guid>("RoomParticipantRoomId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RoomParticipantUserId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("RoomParticipantRoomId", "RoomParticipantUserId");

                                    b2.ToTable("RoomParticipants");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomParticipantRoomId", "RoomParticipantUserId");
                                });

                            b1.Navigation("Settings")
                                .IsRequired();

                            b1.Navigation("SmallUserInfo")
                                .IsRequired();
                        });

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
